mooc_mooc_homepage:
    path:     /
    defaults: { _controller: MoocMoocBundle:Default:index }
    
mooc_mooc_log_out_admin:
    path:     /logoutadmin
    defaults: { _controller: MoocMoocBundle:Admin:logoutadmin}
    
mooc_mooc_log_out_comite:
    path:     /logoutcomite
    defaults: { _controller: MoocMoocBundle:Comite:logoutcomite}

mooc_mooc_contact:
    path:     /contact
    defaults: { _controller: MoocMoocBundle:Contact:send }

mooc_mooc_about:
    path:     /about
    defaults: { _controller: MoocMoocBundle:About:info }

mooc_mooc_logadmin:
    path:     /loginadmin
    defaults: { _controller: MoocMoocBundle:Admin:loginAdmin} 
    
mooc_mooc_logcomite:
    path:     /logincomite
    defaults: { _controller: MoocMoocBundle:Comite:loginComite} 
    
mooc_mooc_logOrganisme:
    path:     /logOrganisme
    defaults: { _controller: MoocMoocBundle:Organisme:loginOrganisme}  
     
mooc_mooc_listecours:
    path:     /listecours
    defaults: { _controller: MoocMoocBundle:Cours:affichecours}
    
mooc_mooc_listeformateur:
    path:     /listeformateur
    defaults: { _controller: MoocMoocBundle:Formateur:afficheformateur}

mooc_mooc_logformateur:
    path:     /loginformateur
    defaults: { _controller: MoocMoocBundle:Formateur:loginformateur} 

mooc_mooc_inscritformateur:
    path:     /inscriptionformateur
    defaults: { _controller: MoocMoocBundle:Formateur:inscriptionformateur} 

mooc_mooc_log_out_formateur:
    path:     /logoutformateur
    defaults: { _controller: MoocMoocBundle:Formateur:logoutformateur} 

mooc_mooc_acceuilformateur:
    path:     /acceuilformateur/{cin}
    defaults: { _controller: MoocMoocBundle:Formateur:acceuilformateur} 
    
mooc_mooc_publiercourformateur:
    path:     /publiercour/{cin}
    defaults: { _controller: MoocMoocBundle:Formateur:publiercour} 
    
mooc_mooc_listecourformateur:
    path:     /listecourformateur/{cin}
    defaults: { _controller: MoocMoocBundle:Formateur:listecourformateur}     
    
mooc_mooc_profilformateur:
    path:     /profilformateur/{cin}
    defaults: { _controller: MoocMoocBundle:Formateur:profilformateur} 
    
mooc_mooc_profediterprofile:
    path:     /editerprofile/{cin}
    defaults: { _controller: MoocMoocBundle:Formateur:editerprofile}
    
mooc_mooc_afficherformateur:
    path:     /afficherformateur
    defaults: { _controller: MoocMoocBundle:Formateur:afficherformateur}     
     
mooc_mooc_listeformateurbconnect:
    path:     /listeformateurconnect/{cin}
    defaults: { _controller: MoocMoocBundle:Formateur:listeformateurbconnect}    

mooc_mooc_listeorganismeconnect:
    path:     /listeorganismeconnect/{cin}
    defaults: { _controller: MoocMoocBundle:Formateur:listeorganismeconnect}  
    
mooc_mooc_profileorganismeconnect:
    path:     /profileorganismeconnect/{cin}/{login}
    defaults: { _controller: MoocMoocBundle:Formateur:profileorganismeconnect}   
    
mooc_mooc_pageint:
    path:     /pageint
    defaults: { _controller: MoocMoocBundle:Formateur:pageint}   

mooc_mooc_inviterOrganisme:
    path:     /inviterOrganisme/{cin}/{login}
    defaults: { _controller: MoocMoocBundle:Formateur:inviterOrganisme}    
    
mooc_mooc_listeinvitation:
    path:     /listeinvitation/{cin}
    defaults: { _controller: MoocMoocBundle:Formateur:listeinvitation} 
    
mooc_mooc_repondreorganisme:
    path:     /repondreorganisme/{cin}/{login}
    defaults: { _controller: MoocMoocBundle:Formateur:repondreorganisme}  
    
mooc_mooc_refuserinvitation:
    path:     /refuserinvitation/{cin}/{login}
    defaults: { _controller: MoocMoocBundle:Formateur:refuserinvitation}

mooc_mooc_accepterinvitation:
    path:     /accepterinvitation/{cin}/{login}
    defaults: { _controller: MoocMoocBundle:Formateur:accepterinvitation}

mooc_mooc_nombreinvitation:
    path:     /nombreinvitation
    defaults: { _controller: MoocMoocBundle:Formateur:nombreinvitation}

mooc_mooc_rechercherOrganisme:
    path:     /rechercherOrganisme{cin}
    defaults: { _controller: MoocMoocBundle:Formateur:rechercherOrganisme}
    
    
mooc_mooc_modifier_qz:
    path:     /ModifierQZ/{id}
    defaults: { _controller: MoocMoocBundle:Quiz:modifierQuiz}
    
mooc_mooc_modifier_question:
    path:     /ModifierQuestion/{idquestion}/{idquiz}
    defaults: { _controller: MoocMoocBundle:Question:modifierQuestion}
    
mooc_mooc_supprimer_question:
    path:     /SupprimerQuestion/{idquestion}/{idquiz}
    defaults: { _controller: MoocMoocBundle:Question:supprimerQuestion}
    
mooc_mooc_modifier_test:
    path:     /testmodifier/{id}
    defaults: { _controller: MoocMoocBundle:Quiz:testmodifier} 
    
mooc_mooc_passer_quiz:
    path:     /validerQuiz/{id}
    defaults: { _controller: MoocMoocBundle:Quiz:PasserQuiz} 

mooc_mooc_note:
    path:     /note/{note}/{id}
    defaults: { _controller: MoocMoocBundle:Quiz:Note} 

mooc_mooc_afficher_chapitreForm:
    path:     /AfficherChapitreForm/{id}
    defaults: { _controller: MoocMoocBundle:Chapitre:afficheChapitreForm}
    
    
    
mooc_mooc_listechapitre:
    path:     /listechapitres/{id}
    defaults: { _controller: MoocMoocBundle:Chapitre:affichelistChapitres}
    
mooc_mooc_listechapitreApp:
    path:     /listechapitresApp/{id}
    defaults: { _controller: MoocMoocBundle:Chapitre:affichelistChapitresApp}
    
mooc_mooc_Ajouter_chapitre:
    path:     /AjouterChapitre/{id}
    defaults: { _controller: MoocMoocBundle:Chapitre:ajouterChapitre}
   
mooc_mooc_Modifier_chapitre:
    path:     /ModifierChapitre/{id}/{idcours}
    defaults: { _controller: MoocMoocBundle:Chapitre:modifierChapitre}
    
mooc_mooc_Ajouter_quiz:
    path:     /AjouterQuiz
    defaults: { _controller: MoocMoocBundle:Quiz:ajouterQuiz}
    
mooc_mooc_Ajouter_question:
    path:     /AjouterQuestion/{idquiz}
    defaults: { _controller: MoocMoocBundle:Question:ajouterQuestion}
    
mooc_mooc_listeQuiz:
    path:     /listequiz
    defaults: { _controller: MoocMoocBundle:Quiz:affichelistquiz}
    
mooc_mooc_Supprimer_chapitre:
    path:     /SupprimerChapitre/{id}/{idcours}
    defaults: { _controller: MoocMoocBundle:Chapitre:supprimerChapitre}
    
mooc_mooc_Supprimer_quiz:
    path:     /SupprimerQuiz/{id}
    defaults: { _controller: MoocMoocBundle:Quiz:supprimerQuiz}
    
mooc_mooc_afficher_chapitre:
    path:     /AfficherChapitre/{id}
    defaults: { _controller: MoocMoocBundle:Chapitre:afficheChapitre}
    
mooc_mooc_afficher_chapitreForm:
    path:     /AfficherChapitreForm/{id}
    defaults: { _controller: MoocMoocBundle:Chapitre:afficheChapitreForm}
    
mooc_mooc_afficher_quiz:
    path:     /AfficherQuiz/{id}
    defaults: { _controller: MoocMoocBundle:Quiz:afficheQuiz}
    
mooc_mooc_afficher_test:
    path:     /test/{id}
    defaults: { _controller: MoocMoocBundle:Quiz:test}  
    
    
mooc_mooc_afficher_quiz_chrono:
    path:     /AfficherQuizChrono/{id}
    defaults: { _controller: MoocMoocBundle:Quiz:afficheQuizChrono}
    
mooc_mooc_note:
    path:     /note/{note}/{id}
    defaults: { _controller: MoocMoocBundle:Quiz:Note} 
    
mooc_mooc_modifier_quiz:
    path:     /ModifierQuiz/{id}
    defaults: { _controller: MoocMoocBundle:Quiz:afficheQuizModifier}
    
mooc_mooc_modifier_question:
    path:     /ModifierQuestion/{idquestion}/{idquiz}
    defaults: { _controller: MoocMoocBundle:Question:modifierQuestion}
    
mooc_mooc_modifier_test:
    path:     /testmodifier/{id}
    defaults: { _controller: MoocMoocBundle:Quiz:testmodifier}  
    
mooc_mooc_delCours:
    path:     /DeleteCours/{id}
    defaults: { _controller: MoocMoocBundle:Cours:delete}
    
    
mooc_mooc_updateCours:
    path:     /UpdateCours/{id}
    defaults: { _controller: MoocMoocBundle:Cours:updateCours}
    

mooc_mooc_PassOublier:
    path:     /PassOublier
    defaults: { _controller: MoocMoocBundle:Mail:PassOublier} 
mooc_mooc_Send:
    path:     /Send
    defaults: { _controller: MoocMoocBundle:Mail:Send}
mooc_mooc_CodeConfirme:
    path:     /CodeConfirme
    defaults: { _controller: MoocMoocBundle:Mail:CodeConfirme} 
mooc_mooc_modifPass:
    path:     /modifPass/{name}
    defaults: { _controller: MoocMoocBundle:Mail:modifPass}
mooc_mooc_ModifPassword:
    path:     /ModifPassword/{name}
    defaults: { _controller: MoocMoocBundle:Mail:ModifPassword}
    
    
    
    
mooc_inscription_apprenant:
    path:     /inscriptionApprenant
    defaults: { _controller: MoocMoocBundle:Apprenant:inscriptionApprenant}    
    
mooc_espace_apprenant:
    path:   /espaceapprenant
    defaults: { _controller: MoocMoocBundle:Apprenant:EspaceApprenant}
    
mooc_login_apprenant:
    path:     /loginApprenant
    defaults: { _controller: MoocMoocBundle:Apprenant:loginApprenant}
    
mooc_log_out_apprenant:
    path:     /logoutApprenant
    defaults: { _controller: MoocMoocBundle:Apprenant:logoutApprenant}  
    
mooc_accueil_apprenant:
    path:   /accueilapprenant/{login}
    defaults: { _controller: MoocMoocBundle:Apprenant:acceuilApprenant}   
  
mooc_editer_profil_apprenant:
    path:     /accueilapprenant
    defaults: { _controller: MoocMoocBundle:Apprenant:editerProfil}

mooc_cours_apprenant:
    path:   /CoursApprenant/{login}
    defaults: { _controller: MoocMoocBundle:Apprenant:CoursApprenant}
    
mooc_chercher_cours_apprenant:
    path:   /ChercherCours/{login}
    defaults: { _controller: MoocMoocBundle:Apprenant:ChercherCoursApprenant}

mooc_detail_cours_apprenant:
    path:   /detailCoursApprenant/{idCourSuivi}/{login}
    defaults: { _controller: MoocMoocBundle:Apprenant:detailCoursApprenant}
    
mooc_editer_cours_apprenant:
    path:   /detailCoursApprenant
    defaults: { _controller: MoocMoocBundle:Apprenant:editCoursApprenant}
    
mooc_suivre_cour_apprenant:
    path:     /CoursApprenant
    defaults: { _controller: MoocMoocBundle:Apprenant:suivreCours}    
    
mooc_supprimer_cours_apprenant:
    path:     /CoursApprenan
    defaults: { _controller: MoocMoocBundle:Apprenant:supprimer}
    
mooc_editer_password_apprenant:
    path:   /{login}
    defaults: { _controller: MoocMoocBundle:Apprenant:editPassword}    
       
    
    
    
mooc_consult_cours_apprenant:
    path:     /consulterCours/{cours}/{login}
    defaults: { _controller: MoocMoocBundle:Apprenant:consult}
   
mooc_pdf:
    path:     /pdf/{id}
    defaults: { _controller: MoocMoocBundle:Cours:pdf}
 
mooc_apprenant_cours_details:
    path:     /coursDet/{idCours}
    defaults: { _controller: MoocMoocBundle:Apprenant:coursDetails}
    

    


mooc_mooc_PreinscriptionOrganisme:
    path:     /PreinscriptionOrganisme
    defaults: { _controller: MoocMoocBundle:Organisme:PreinscriptionOrganisme} 
mooc_mooc_PreinscriptionOrganismeEnreg:
    path:     /PreinscriptionOrganismeEnreg
    defaults: { _controller: MoocMoocBundle:Organisme:PreinscriptionOrganismeEnreg}    
mooc_mooc_inscriptionOrganisme:
    path:     /inscriptionOrganisme/{id}
    defaults: { _controller: MoocMoocBundle:Organisme:inscriptionOrganisme}
mooc_mooc_inscriptionOrganismeMail:
    path:     /inscriptionOrganismeMail/{id}
    defaults: { _controller: MoocMoocBundle:Organisme:inscriptionOrganismeMail}    

mooc_mooc_acceuilOrganisme:
    path:     /acceuilOrganisme/{name}/{nbr}
    defaults: { _controller: MoocMoocBundle:Organisme:acceuilOrganisme}    
mooc_mooc_profileOrganisme:
    path:     /profileOrganisme/{name}/{nbr}
    defaults: { _controller: MoocMoocBundle:Organisme:profileOrganisme}    
mooc_mooc_listeOrganisme:
    path:     /listeOrganisme
    defaults: { _controller: MoocMoocBundle:Organisme:listeOrganisme} 
mooc_mooc_listeFormateurs:
    path:     /listeFormateurs/{name}
    defaults: { _controller: MoocMoocBundle:Organisme:listeFormateurs}
mooc_mooc_ListeFormateurs1:
    path:     /ListeFormateurs1/{name}/{nbr}
    defaults: { _controller: MoocMoocBundle:Organisme:ListeFormateurs1}
mooc_mooc_ListeTousFormateurs:
    path:     /ListeTousFormateurs/{name}/{nbr}
    defaults: { _controller: MoocMoocBundle:Organisme:ListeTousFormateurs}    
mooc_mooc_ListeOrganismes1:
    path:     /ListeOrganismes1/{name}/{nbr}
    defaults: { _controller: MoocMoocBundle:Organisme:ListeOrganismes1} 
mooc_mooc_mail:
    path:     /mail/{name}
    defaults: { _controller: MoocMoocBundle:Organisme:mail}
mooc_mooc_ChercherFormateur:
    path:     /ChercherFormateur/{name}/{nbr}
    defaults: { _controller: MoocMoocBundle:Organisme:ChercherFormateur}
mooc_mooc_ChercherFormateur2:
    path:     /ChercherFormateur2/{name}/{nbr}
    defaults: { _controller: MoocMoocBundle:Organisme:ChercherFormateur2}    
mooc_mooc_ChercherOrganisme:
    path:     /ChercherOrganisme/{name}/{nbr}
    defaults: { _controller: MoocMoocBundle:Organisme:ChercherOrganisme}    
mooc_mooc_SupprimerFormateur:
    path:     /SupprimerFormateur/{cin}/{name}/{nbr}
    defaults: { _controller: MoocMoocBundle:Organisme:supprimer}
mooc_mooc_ProfilFormateur:
    path:     /ProfilFormateur/{cin}/{name}
    defaults: { _controller: MoocMoocBundle:Organisme:ProfilFormateur}
mooc_mooc_ProfilFormateur1:
    path:     /ProfilFormateur1/{nom}/{name}/{id}
    defaults: { _controller: MoocMoocBundle:Organisme:ProfilFormateur1}
mooc_mooc_ProfilFormateur2:
    path:     /ProfilFormateur2/{cin}/{name}
    defaults: { _controller: MoocMoocBundle:Organisme:ProfilFormateur2}    
mooc_mooc_profileAutreOrganisme:
    path:     /profileAutreOrganisme/{name}/{name2}/{nbr}
    defaults: { _controller: MoocMoocBundle:Organisme:profileAutreOrganisme} 
mooc_mooc_ListeInvit:
    path:     /ListeInvit/{name}/{nbr}
    defaults: { _controller: MoocMoocBundle:Organisme:ListeInvit}
mooc_mooc_InviterFormateur:
    path:     /InviterFormateur/{cin}/{login}/{nbr}
    defaults: { _controller: MoocMoocBundle:Organisme:InviterFormateur}
mooc_mooc_Organisme_AccepterInvit:
    path:     /AccepterInvit/{id}/{name}/{nbr}
    defaults: { _controller: MoocMoocBundle:Organisme:AccepterInvit}    
mooc_mooc_supprimerInvit:
    path:     /supprimerInvit/{id}/{name}/{nbr}
    defaults: { _controller: MoocMoocBundle:Organisme:supprimerInvit}
mooc_mooc_publierCoursOrganisme:
    path:     /publierCoursOrganisme/{name}/{nbr}
    defaults: { _controller: MoocMoocBundle:Organisme:publierCoursOrganisme}

