easy_admin:
    design:
        brand_color: '#3C8DBC'
        menu: 
            - { entity: 'Formateur', icon: 'group' }
            - { entity: 'Cours', icon: 'book' }
            - { entity: 'Organisme', icon: 'home'}
            - { label: 'Front office', url: 'http://localhost/Mooc_web/web/app_dev.php/', icon: 'list' }
    site_name: 'MOO<i><font color="black">Comité</font></i>'
    entities:
        
        Formateur :
            class: Mooc\MoocBundle\Entity\Formateur
            label: 'Formateurs'
            
            list :
                
                title: "Liste des formateurs"
                fields: ['nom', 'prenom', 'email',{ property: 'avatar', type: 'image',label: 'Photo', base_path: 'http://localhost/Mooc_3A2_web/web/uploads/img/avatar/' },Organisme,{property: 'cv' , label: 'CV',template: 'cv.html.twig', base_path: %app.path.formateur_cv%  },{ property: 'etat', type: 'toggle', label: 'Valide' }]
                actions:
                    - { name: 'show', label: '', icon: 'search' }
                    - { name: 'delete', label: '', icon: 'trash' }
                    - { name: 'edit', type: 'method', label: '', class: '', icon: pencil }
            
                
            show :
                show :
                fields: [{property: 'avatar', type: 'image',label: 'Photo', base_path: 'http://localhost/Mooc_3A2_web/web/uploads/img/avatar/'},'nom', 'prenom', 'email',{property: 'cv' , label: 'CV',template: 'cv.html.twig', base_path: %app.path.formateur_cv%  },{ property: 'etat', type: 'toggle', label: 'Valide' },Organisme]
            form:
                fields: ['nom', 'prenom', 'email','Organisme',login,{property: 'password',type: 'password'},{property: 'etat', label: 'Valide'}]
            
        Cours :
            class : Mooc\MoocBundle\Entity\Cours
            list : 
                title: "Liste des cours à valider"
                fields: ['nomCours','description','difficulte','objectif',{property: 'cinformateur', label: 'Formateur'},{property: 'etat', label: 'Etat' , type: 'toggle'}]
                actions:
                
                    - { name: 'show', label: '', icon: 'search' }
                    - { name: 'delete', label: '', icon: 'trash' }
                    - { name: 'edit', type: 'method', label: '', class: '', icon: '' }
                    
            form : 
                fields: ['nomCours','description','difficulte','objectif',{property: 'cinformateur', label: 'CIN formateur'},{property: 'etat', label: 'Valide'}]
        
        Organisme:
            class: Mooc\MoocBundle\Entity\Organisme
            disabled_actions: ['edit', 'delete', 'new']
            label: 'Organismes'
            list:
                actions: [ { name: 'show',label: 'Détails', icon: 'search' } ]
                title: "Liste des Organismes"
                fields: [{property: 'logo', type: 'image',label: 'Logo', base_path: 'http://localhost/Mooc_3A2_web/web/uploads/img/logo/'},{property: 'nom', label: 'Nom organisme'},email,{property: 'siteweb',label: 'Site web'},adresse,telephone,{property: 'etat', template: 'etat.html.twig'}]
            show:
                fields: [{property: 'logo', type: 'image',label: 'Logo', base_path: 'http://localhost/Mooc_3A2_web/web/uploads/img/logo/'},{property: 'nom', label: 'Nom organisme'},email,{property: 'siteweb',label: 'Site web'},adresse,telephone,description,{property: 'etat',label: 'Valide',type: 'toggle'}]