<?php

namespace Mooc\MoocBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CoursuiviRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoursuiviRepository extends EntityRepository
{
    public function nombreCoursAndroidJanvier() {
        $query = $this->getEntityManager()
                ->createQuery("select count(c.nomCours) from MoocMoocBundle:Coursuivi cs,MoocMoocBundle:Cours c where cs.idCours=c.idcours and c.nomCours='Android' and cs.dateDebut between :deb and :fin ");
        $query->setParameters(array(
            'deb' => new \DateTime('2016-01-01'),
            'fin' => new \DateTime('2016-01-31')
                )
        );
        return $query->getSingleScalarResult();
    }
    
    public function nombreCoursAndroidFevrier() {
        $query = $this->getEntityManager()
                ->createQuery("select count(c.nomCours) from MoocMoocBundle:Coursuivi cs,MoocMoocBundle:Cours c where cs.idCours=c.idcours and c.nomCours='Android' and cs.dateDebut between :deb and :fin ");
        $query->setParameters(array(
            'deb' => new \DateTime('2016-02-01'),
            'fin' => new \DateTime('2016-02-29')
                )
        );
        return $query->getSingleScalarResult();
    }
    
    public function nombreCoursAndroidMars() {
        $query = $this->getEntityManager()
                ->createQuery("select count(c.nomCours) from MoocMoocBundle:Coursuivi cs,MoocMoocBundle:Cours c where cs.idCours=c.idcours and c.nomCours='Android' and cs.dateDebut between :deb and :fin ");
        $query->setParameters(array(
            'deb' => new \DateTime('2016-03-01'),
            'fin' => new \DateTime('2016-03-31')
                )
        );
        return $query->getSingleScalarResult();
    }
    
    public function nombreCoursAndroidAvril() {
        $query = $this->getEntityManager()
                ->createQuery("select count(c.nomCours) from MoocMoocBundle:Coursuivi cs,MoocMoocBundle:Cours c where cs.idCours=c.idcours and c.nomCours='Android' and cs.dateDebut between :deb and :fin ");
        $query->setParameters(array(
            'deb' => new \DateTime('2016-04-01'),
            'fin' => new \DateTime('2016-04-31')
                )
        );
        return $query->getSingleScalarResult();
    }
    
    public function nombreCoursAndroidMai() {
        $query = $this->getEntityManager()
                ->createQuery("select count(c.nomCours) from MoocMoocBundle:Coursuivi cs,MoocMoocBundle:Cours c where cs.idCours=c.idcours and c.nomCours='Android' and cs.dateDebut between :deb and :fin ");
        $query->setParameters(array(
            'deb' => new \DateTime('2016-05-01'),
            'fin' => new \DateTime('2016-05-31')
                )
        );
        return $query->getSingleScalarResult();
    }
    
    public function nombreCoursAndroidJuin() {
        $query = $this->getEntityManager()
                ->createQuery("select count(c.nomCours) from MoocMoocBundle:Coursuivi cs,MoocMoocBundle:Cours c where cs.idCours=c.idcours and c.nomCours='Android' and cs.dateDebut between :deb and :fin ");
        $query->setParameters(array(
            'deb' => new \DateTime('2016-06-01'),
            'fin' => new \DateTime('2016-06-31')
                )
        );
        return $query->getSingleScalarResult();
    }
    
    public function nombreCoursAndroidJuillet() {
        $query = $this->getEntityManager()
                ->createQuery("select count(c.nomCours) from MoocMoocBundle:Coursuivi cs,MoocMoocBundle:Cours c where cs.idCours=c.idcours and c.nomCours='Android' and cs.dateDebut between :deb and :fin ");
        $query->setParameters(array(
            'deb' => new \DateTime('2016-07-01'),
            'fin' => new \DateTime('2016-07-31')
                )
        );
        return $query->getSingleScalarResult();
    }
    
    public function nombreCoursAndroidAout() {
        $query = $this->getEntityManager()
                ->createQuery("select count(c.nomCours) from MoocMoocBundle:Coursuivi cs,MoocMoocBundle:Cours c where cs.idCours=c.idcours and c.nomCours='Android' and cs.dateDebut between :deb and :fin ");
        $query->setParameters(array(
            'deb' => new \DateTime('2016-08-01'),
            'fin' => new \DateTime('2016-08-31')
                )
        );
        return $query->getSingleScalarResult();
    }
    
    public function nombreCoursAndroidSeptembre() {
        $query = $this->getEntityManager()
                ->createQuery("select count(c.nomCours) from MoocMoocBundle:Coursuivi cs,MoocMoocBundle:Cours c where cs.idCours=c.idcours and c.nomCours='Android' and cs.dateDebut between :deb and :fin ");
        $query->setParameters(array(
            'deb' => new \DateTime('2016-09-01'),
            'fin' => new \DateTime('2016-09-31')
                )
        );
        return $query->getSingleScalarResult();
    }
    
    public function nombreCoursAndroidOctobre() {
        $query = $this->getEntityManager()
                ->createQuery("select count(c.nomCours) from MoocMoocBundle:Coursuivi cs,MoocMoocBundle:Cours c where cs.idCours=c.idcours and c.nomCours='Android' and cs.dateDebut between :deb and :fin ");
        $query->setParameters(array(
            'deb' => new \DateTime('2016-10-01'),
            'fin' => new \DateTime('2016-10-31')
                )
        );
        return $query->getSingleScalarResult();
    }
    
    public function nombreCoursAndroidNovembre() {
        $query = $this->getEntityManager()
                ->createQuery("select count(c.nomCours) from MoocMoocBundle:Coursuivi cs,MoocMoocBundle:Cours c where cs.idCours=c.idcours and c.nomCours='Android' and cs.dateDebut between :deb and :fin ");
        $query->setParameters(array(
            'deb' => new \DateTime('2016-11-01'),
            'fin' => new \DateTime('2016-11-31')
                )
        );
        return $query->getSingleScalarResult();
    }
    
    public function nombreCoursAndroidDecembre() {
        $query = $this->getEntityManager()
                ->createQuery("select count(c.nomCours) from MoocMoocBundle:Coursuivi cs,MoocMoocBundle:Cours c where cs.idCours=c.idcours and c.nomCours='Android' and cs.dateDebut between :deb and :fin ");
        $query->setParameters(array(
            'deb' => new \DateTime('2016-12-01'),
            'fin' => new \DateTime('2016-12-31')
                )
        );
        return $query->getSingleScalarResult();
    }
    
    public function nombreCoursiOSJanvier() {
        $query = $this->getEntityManager()
                ->createQuery("select count(c.nomCours) from MoocMoocBundle:Coursuivi cs,MoocMoocBundle:Cours c where cs.idCours=c.idcours and c.nomCours='iOS' and cs.dateDebut between :deb and :fin ");
        $query->setParameters(array(
            'deb' => new \DateTime('2016-01-01'),
            'fin' => new \DateTime('2016-01-31')
                )
        );
        return $query->getSingleScalarResult();
    }
    
    public function nombreCoursiOSFevrier() {
        $query = $this->getEntityManager()
                ->createQuery("select count(c.nomCours) from MoocMoocBundle:Coursuivi cs,MoocMoocBundle:Cours c where cs.idCours=c.idcours and c.nomCours='iOS' and cs.dateDebut between :deb and :fin ");
        $query->setParameters(array(
            'deb' => new \DateTime('2016-02-01'),
            'fin' => new \DateTime('2016-02-29')
                )
        );
        return $query->getSingleScalarResult();
    }
    
    public function nombreCoursiOSMars() {
        $query = $this->getEntityManager()
                ->createQuery("select count(c.nomCours) from MoocMoocBundle:Coursuivi cs,MoocMoocBundle:Cours c where cs.idCours=c.idcours and c.nomCours='iOS' and cs.dateDebut between :deb and :fin ");
        $query->setParameters(array(
            'deb' => new \DateTime('2016-03-01'),
            'fin' => new \DateTime('2016-03-31')
                )
        );
        return $query->getSingleScalarResult();
    }
    
    public function nombreCoursiOSAvril() {
        $query = $this->getEntityManager()
                ->createQuery("select count(c.nomCours) from MoocMoocBundle:Coursuivi cs,MoocMoocBundle:Cours c where cs.idCours=c.idcours and c.nomCours='iOS' and cs.dateDebut between :deb and :fin ");
        $query->setParameters(array(
            'deb' => new \DateTime('2016-04-01'),
            'fin' => new \DateTime('2016-04-31')
                )
        );
        return $query->getSingleScalarResult();
    }
    
    public function nombreCoursiOSMai() {
        $query = $this->getEntityManager()
                ->createQuery("select count(c.nomCours) from MoocMoocBundle:Coursuivi cs,MoocMoocBundle:Cours c where cs.idCours=c.idcours and c.nomCours='iOS' and cs.dateDebut between :deb and :fin ");
        $query->setParameters(array(
            'deb' => new \DateTime('2016-05-01'),
            'fin' => new \DateTime('2016-05-31')
                )
        );
        return $query->getSingleScalarResult();
    }
    
    public function nombreCoursiOSJuin() {
        $query = $this->getEntityManager()
                ->createQuery("select count(c.nomCours) from MoocMoocBundle:Coursuivi cs,MoocMoocBundle:Cours c where cs.idCours=c.idcours and c.nomCours='iOS' and cs.dateDebut between :deb and :fin ");
        $query->setParameters(array(
            'deb' => new \DateTime('2016-06-01'),
            'fin' => new \DateTime('2016-06-31')
                )
        );
        return $query->getSingleScalarResult();
    }
    
    public function nombreCoursiOSJuillet() {
        $query = $this->getEntityManager()
                ->createQuery("select count(c.nomCours) from MoocMoocBundle:Coursuivi cs,MoocMoocBundle:Cours c where cs.idCours=c.idcours and c.nomCours='iOS' and cs.dateDebut between :deb and :fin ");
        $query->setParameters(array(
            'deb' => new \DateTime('2016-07-01'),
            'fin' => new \DateTime('2016-07-31')
                )
        );
        return $query->getSingleScalarResult();
    }
    
    public function nombreCoursiOSAout() {
        $query = $this->getEntityManager()
                ->createQuery("select count(c.nomCours) from MoocMoocBundle:Coursuivi cs,MoocMoocBundle:Cours c where cs.idCours=c.idcours and c.nomCours='iOS' and cs.dateDebut between :deb and :fin ");
        $query->setParameters(array(
            'deb' => new \DateTime('2016-08-01'),
            'fin' => new \DateTime('2016-08-31')
                )
        );
        return $query->getSingleScalarResult();
    }
    
    public function nombreCoursiOSSeptembre() {
        $query = $this->getEntityManager()
                ->createQuery("select count(c.nomCours) from MoocMoocBundle:Coursuivi cs,MoocMoocBundle:Cours c where cs.idCours=c.idcours and c.nomCours='iOS' and cs.dateDebut between :deb and :fin ");
        $query->setParameters(array(
            'deb' => new \DateTime('2016-09-01'),
            'fin' => new \DateTime('2016-09-31')
                )
        );
        return $query->getSingleScalarResult();
    }
    
    public function nombreCoursiOSOctobre() {
        $query = $this->getEntityManager()
                ->createQuery("select count(c.nomCours) from MoocMoocBundle:Coursuivi cs,MoocMoocBundle:Cours c where cs.idCours=c.idcours and c.nomCours='iOS' and cs.dateDebut between :deb and :fin ");
        $query->setParameters(array(
            'deb' => new \DateTime('2016-10-01'),
            'fin' => new \DateTime('2016-10-31')
                )
        );
        return $query->getSingleScalarResult();
    }
    
    public function nombreCoursiOSNovembre() {
        $query = $this->getEntityManager()
                ->createQuery("select count(c.nomCours) from MoocMoocBundle:Coursuivi cs,MoocMoocBundle:Cours c where cs.idCours=c.idcours and c.nomCours='iOS' and cs.dateDebut between :deb and :fin ");
        $query->setParameters(array(
            'deb' => new \DateTime('2016-11-01'),
            'fin' => new \DateTime('2016-11-31')
                )
        );
        return $query->getSingleScalarResult();
    }
    
    public function nombreCoursiOSDecembre() {
        $query = $this->getEntityManager()
                ->createQuery("select count(c.nomCours) from MoocMoocBundle:Coursuivi cs,MoocMoocBundle:Cours c where cs.idCours=c.idcours and c.nomCours='iOS' and cs.dateDebut between :deb and :fin ");
        $query->setParameters(array(
            'deb' => new \DateTime('2016-12-01'),
            'fin' => new \DateTime('2016-12-31')
                )
        );
        return $query->getSingleScalarResult();
    }
    
    // WP
    
    public function nombreCoursWPJanvier() {
        $query = $this->getEntityManager()
                ->createQuery("select count(c.nomCours) from MoocMoocBundle:Coursuivi cs,MoocMoocBundle:Cours c where cs.idCours=c.idcours and c.nomCours='Windows Phone' and cs.dateDebut between :deb and :fin ");
        $query->setParameters(array(
            'deb' => new \DateTime('2016-01-01'),
            'fin' => new \DateTime('2016-01-31')
                )
        );
        return $query->getSingleScalarResult();
    }
    
    public function nombreCoursWPFevrier() {
        $query = $this->getEntityManager()
                ->createQuery("select count(c.nomCours) from MoocMoocBundle:Coursuivi cs,MoocMoocBundle:Cours c where cs.idCours=c.idcours and c.nomCours='Windows Phone' and cs.dateDebut between :deb and :fin ");
        $query->setParameters(array(
            'deb' => new \DateTime('2016-02-01'),
            'fin' => new \DateTime('2016-02-29')
                )
        );
        return $query->getSingleScalarResult();
    }
    
    public function nombreCoursWPMars() {
        $query = $this->getEntityManager()
                ->createQuery("select count(c.nomCours) from MoocMoocBundle:Coursuivi cs,MoocMoocBundle:Cours c where cs.idCours=c.idcours and c.nomCours='Windows Phone' and cs.dateDebut between :deb and :fin ");
        $query->setParameters(array(
            'deb' => new \DateTime('2016-03-01'),
            'fin' => new \DateTime('2016-03-31')
                )
        );
        return $query->getSingleScalarResult();
    }
    
    public function nombreCoursWPAvril() {
        $query = $this->getEntityManager()
                ->createQuery("select count(c.nomCours) from MoocMoocBundle:Coursuivi cs,MoocMoocBundle:Cours c where cs.idCours=c.idcours and c.nomCours='Windows Phone' and cs.dateDebut between :deb and :fin ");
        $query->setParameters(array(
            'deb' => new \DateTime('2016-04-01'),
            'fin' => new \DateTime('2016-04-31')
                )
        );
        return $query->getSingleScalarResult();
    }
    
    public function nombreCoursWPMai() {
        $query = $this->getEntityManager()
                ->createQuery("select count(c.nomCours) from MoocMoocBundle:Coursuivi cs,MoocMoocBundle:Cours c where cs.idCours=c.idcours and c.nomCours='Windows Phone' and cs.dateDebut between :deb and :fin ");
        $query->setParameters(array(
            'deb' => new \DateTime('2016-05-01'),
            'fin' => new \DateTime('2016-05-31')
                )
        );
        return $query->getSingleScalarResult();
    }
    
    public function nombreCoursWPJuin() {
        $query = $this->getEntityManager()
                ->createQuery("select count(c.nomCours) from MoocMoocBundle:Coursuivi cs,MoocMoocBundle:Cours c where cs.idCours=c.idcours and c.nomCours='Windows Phone' and cs.dateDebut between :deb and :fin ");
        $query->setParameters(array(
            'deb' => new \DateTime('2016-06-01'),
            'fin' => new \DateTime('2016-06-31')
                )
        );
        return $query->getSingleScalarResult();
    }
    
    public function nombreCoursWPJuillet() {
        $query = $this->getEntityManager()
                ->createQuery("select count(c.nomCours) from MoocMoocBundle:Coursuivi cs,MoocMoocBundle:Cours c where cs.idCours=c.idcours and c.nomCours='Windows Phone' and cs.dateDebut between :deb and :fin ");
        $query->setParameters(array(
            'deb' => new \DateTime('2016-07-01'),
            'fin' => new \DateTime('2016-07-31')
                )
        );
        return $query->getSingleScalarResult();
    }
    
    public function nombreCoursWPAout() {
        $query = $this->getEntityManager()
                ->createQuery("select count(c.nomCours) from MoocMoocBundle:Coursuivi cs,MoocMoocBundle:Cours c where cs.idCours=c.idcours and c.nomCours='Windows Phone' and cs.dateDebut between :deb and :fin ");
        $query->setParameters(array(
            'deb' => new \DateTime('2016-08-01'),
            'fin' => new \DateTime('2016-08-31')
                )
        );
        return $query->getSingleScalarResult();
    }
    
    public function nombreCoursWPSeptembre() {
        $query = $this->getEntityManager()
                ->createQuery("select count(c.nomCours) from MoocMoocBundle:Coursuivi cs,MoocMoocBundle:Cours c where cs.idCours=c.idcours and c.nomCours='Windows Phone' and cs.dateDebut between :deb and :fin ");
        $query->setParameters(array(
            'deb' => new \DateTime('2016-09-01'),
            'fin' => new \DateTime('2016-09-31')
                )
        );
        return $query->getSingleScalarResult();
    }
    
    public function nombreCoursWPOctobre() {
        $query = $this->getEntityManager()
                ->createQuery("select count(c.nomCours) from MoocMoocBundle:Coursuivi cs,MoocMoocBundle:Cours c where cs.idCours=c.idcours and c.nomCours='Windows Phone' and cs.dateDebut between :deb and :fin ");
        $query->setParameters(array(
            'deb' => new \DateTime('2016-10-01'),
            'fin' => new \DateTime('2016-10-31')
                )
        );
        return $query->getSingleScalarResult();
    }
    
    public function nombreCoursWPNovembre() {
        $query = $this->getEntityManager()
                ->createQuery("select count(c.nomCours) from MoocMoocBundle:Coursuivi cs,MoocMoocBundle:Cours c where cs.idCours=c.idcours and c.nomCours='Windows Phone' and cs.dateDebut between :deb and :fin ");
        $query->setParameters(array(
            'deb' => new \DateTime('2016-11-01'),
            'fin' => new \DateTime('2016-11-31')
                )
        );
        return $query->getSingleScalarResult();
    }
    
    public function nombreCoursWPDecembre() {
        $query = $this->getEntityManager()
                ->createQuery("select count(c.nomCours) from MoocMoocBundle:Coursuivi cs,MoocMoocBundle:Cours c where cs.idCours=c.idcours and c.nomCours='Windows Phone' and cs.dateDebut between :deb and :fin ");
        $query->setParameters(array(
            'deb' => new \DateTime('2016-12-01'),
            'fin' => new \DateTime('2016-12-31')
                )
        );
        return $query->getSingleScalarResult();
    }
    
    // J2ME
    
    public function nombreCoursJJanvier() {
        $query = $this->getEntityManager()
                ->createQuery("select count(c.nomCours) from MoocMoocBundle:Coursuivi cs,MoocMoocBundle:Cours c where cs.idCours=c.idcours and c.nomCours='J2ME' and cs.dateDebut between :deb and :fin ");
        $query->setParameters(array(
            'deb' => new \DateTime('2016-01-01'),
            'fin' => new \DateTime('2016-01-31')
                )
        );
        return $query->getSingleScalarResult();
    }
    
    public function nombreCoursJFevrier() {
        $query = $this->getEntityManager()
                ->createQuery("select count(c.nomCours) from MoocMoocBundle:Coursuivi cs,MoocMoocBundle:Cours c where cs.idCours=c.idcours and c.nomCours='J2ME' and cs.dateDebut between :deb and :fin ");
        $query->setParameters(array(
            'deb' => new \DateTime('2016-02-01'),
            'fin' => new \DateTime('2016-02-29')
                )
        );
        return $query->getSingleScalarResult();
    }
    
    public function nombreCoursJMars() {
        $query = $this->getEntityManager()
                ->createQuery("select count(c.nomCours) from MoocMoocBundle:Coursuivi cs,MoocMoocBundle:Cours c where cs.idCours=c.idcours and c.nomCours='J2ME' and cs.dateDebut between :deb and :fin ");
        $query->setParameters(array(
            'deb' => new \DateTime('2016-03-01'),
            'fin' => new \DateTime('2016-03-31')
                )
        );
        return $query->getSingleScalarResult();
    }
    
    public function nombreCoursJAvril() {
        $query = $this->getEntityManager()
                ->createQuery("select count(c.nomCours) from MoocMoocBundle:Coursuivi cs,MoocMoocBundle:Cours c where cs.idCours=c.idcours and c.nomCours='J2ME' and cs.dateDebut between :deb and :fin ");
        $query->setParameters(array(
            'deb' => new \DateTime('2016-04-01'),
            'fin' => new \DateTime('2016-04-31')
                )
        );
        return $query->getSingleScalarResult();
    }
    
    public function nombreCoursJMai() {
        $query = $this->getEntityManager()
                ->createQuery("select count(c.nomCours) from MoocMoocBundle:Coursuivi cs,MoocMoocBundle:Cours c where cs.idCours=c.idcours and c.nomCours='J2ME' and cs.dateDebut between :deb and :fin ");
        $query->setParameters(array(
            'deb' => new \DateTime('2016-05-01'),
            'fin' => new \DateTime('2016-05-31')
                )
        );
        return $query->getSingleScalarResult();
    }
    
    public function nombreCoursJJuin() {
        $query = $this->getEntityManager()
                ->createQuery("select count(c.nomCours) from MoocMoocBundle:Coursuivi cs,MoocMoocBundle:Cours c where cs.idCours=c.idcours and c.nomCours='J2ME' and cs.dateDebut between :deb and :fin ");
        $query->setParameters(array(
            'deb' => new \DateTime('2016-06-01'),
            'fin' => new \DateTime('2016-06-31')
                )
        );
        return $query->getSingleScalarResult();
    }
    
    public function nombreCoursJJuillet() {
        $query = $this->getEntityManager()
                ->createQuery("select count(c.nomCours) from MoocMoocBundle:Coursuivi cs,MoocMoocBundle:Cours c where cs.idCours=c.idcours and c.nomCours='J2ME' and cs.dateDebut between :deb and :fin ");
        $query->setParameters(array(
            'deb' => new \DateTime('2016-07-01'),
            'fin' => new \DateTime('2016-07-31')
                )
        );
        return $query->getSingleScalarResult();
    }
    
    public function nombreCoursJAout() {
        $query = $this->getEntityManager()
                ->createQuery("select count(c.nomCours) from MoocMoocBundle:Coursuivi cs,MoocMoocBundle:Cours c where cs.idCours=c.idcours and c.nomCours='J2ME' and cs.dateDebut between :deb and :fin ");
        $query->setParameters(array(
            'deb' => new \DateTime('2016-08-01'),
            'fin' => new \DateTime('2016-08-31')
                )
        );
        return $query->getSingleScalarResult();
    }
    
    public function nombreCoursJSeptembre() {
        $query = $this->getEntityManager()
                ->createQuery("select count(c.nomCours) from MoocMoocBundle:Coursuivi cs,MoocMoocBundle:Cours c where cs.idCours=c.idcours and c.nomCours='J2ME' and cs.dateDebut between :deb and :fin ");
        $query->setParameters(array(
            'deb' => new \DateTime('2016-09-01'),
            'fin' => new \DateTime('2016-09-31')
                )
        );
        return $query->getSingleScalarResult();
    }
    
    public function nombreCoursJOctobre() {
        $query = $this->getEntityManager()
                ->createQuery("select count(c.nomCours) from MoocMoocBundle:Coursuivi cs,MoocMoocBundle:Cours c where cs.idCours=c.idcours and c.nomCours='J2ME' and cs.dateDebut between :deb and :fin ");
        $query->setParameters(array(
            'deb' => new \DateTime('2016-10-01'),
            'fin' => new \DateTime('2016-10-31')
                )
        );
        return $query->getSingleScalarResult();
    }
    
    public function nombreCoursJNovembre() {
        $query = $this->getEntityManager()
                ->createQuery("select count(c.nomCours) from MoocMoocBundle:Coursuivi cs,MoocMoocBundle:Cours c where cs.idCours=c.idcours and c.nomCours='J2ME' and cs.dateDebut between :deb and :fin ");
        $query->setParameters(array(
            'deb' => new \DateTime('2016-11-01'),
            'fin' => new \DateTime('2016-11-31')
                )
        );
        return $query->getSingleScalarResult();
    }
    
    public function nombreCoursJDecembre() {
        $query = $this->getEntityManager()
                ->createQuery("select count(c.nomCours) from MoocMoocBundle:Coursuivi cs,MoocMoocBundle:Cours c where cs.idCours=c.idcours and c.nomCours='J2ME' and cs.dateDebut between :deb and :fin ");
        $query->setParameters(array(
            'deb' => new \DateTime('2016-12-01'),
            'fin' => new \DateTime('2016-12-31')
                )
        );
        return $query->getSingleScalarResult();
    }
}
