<?php

namespace Mooc\MoocBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoursRepository extends EntityRepository
{
    public function nombreCours(){
        $query = $this->getEntityManager()
                ->createQuery("select count(c) from MoocMoocBundle:Cours c");
        return $query->getSingleScalarResult();
    }
    
    public function typesCours() {
        $query = $this->getEntityManager()
                ->createQuery("select c.nomCours from MoocMoocBundle:Cours c group by c.nomCours ");
        return $query->getArrayResult();
    }
    
    public function nombreCoursType() {
        $query = $this->getEntityManager()
                ->createQuery("select count(c.nomCours) from MoocMoocBundle:Cours c group by c.nomCours ");
        return $query->getResult(); 
    }
    
    public function testDonut() {
        $query = $this->getEntityManager()
                ->createQuery("select c.nomCours, count(c.nomCours) from MoocMoocBundle:Cours c group by c.nomCours ");
        return $query->getArrayResult();
    }
    
     public function nombreCoursAndroid() {
        $query = $this->getEntityManager()
                ->createQuery("select count(c.nomCours) from MoocMoocBundle:Cours c where c.nomCours='Android' ");
        return $query->getSingleScalarResult();
    }
    
    public function nombreCoursiOS() {
        $query = $this->getEntityManager()
                ->createQuery("select count(c.nomCours) from MoocMoocBundle:Cours c where c.nomCours='iOS' ");
        return $query->getSingleScalarResult();
    }
    
    public function nombreCoursJ2ME() {
        $query = $this->getEntityManager()
                ->createQuery("select count(c.nomCours) from MoocMoocBundle:Cours c where c.nomCours='J2ME' ");
        return $query->getSingleScalarResult();
    }
    
    public function nombreCoursWP() {
        $query = $this->getEntityManager()
                ->createQuery("select count(c.nomCours) from MoocMoocBundle:Cours c where c.nomCours='Windows Phone' ");
        return $query->getSingleScalarResult();
    }
}
