<?php

namespace Mooc\MoocBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormateurRepository extends EntityRepository
{
    public function nombreFormateur(){
        $query = $this->getEntityManager()
                ->createQuery("select count(f) from MoocMoocBundle:Formateur f");
        return $query->getSingleScalarResult();
    }
    
    public function nombreFormateurNonValide(){
        $query = $this->getEntityManager()
                ->createQuery("select count(f) from MoocMoocBundle:Formateur f where f.etat=0");
        return $query->getSingleScalarResult();
    }
    
    public function findFormateurByIdOrganisme($id) {
        $query = $this->getEntityManager()
                ->createQuery("select f from MoocMoocBundle:formateur f where f.Organisme = ?1");
//        $query->setParameter(1, $id);
//        $query->execute();
        return $query->execute(array(1=>$id));
    }
}
