<?php

namespace Mooc\MoocBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormateurRepository extends EntityRepository
{
    public function nombreFormateur(){
        $query = $this->getEntityManager()
                ->createQuery("select count(f) from MoocMoocBundle:Formateur f");
        return $query->getSingleScalarResult();
    }
}
