<?php

namespace Mooc\MoocBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrganismeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganismeRepository extends EntityRepository
{
    public function nombreOrganisme(){
        $query = $this->getEntityManager()
                ->createQuery("select count(o) from MoocMoocBundle:Organisme o");
        return $query->getSingleScalarResult();
    }
}
